### ISSUE TITLE
[Feature] Allow to automatically preserve API data already present in API Manager that is not provided in API-Config JSON file

### ISSUE THREAD

**Issue by remisbaima** [Axway-API-Management-Plus/apimanager-swagger-promote#125]
**User story**
- we have a couple of published APIs (e.g. 20+)
- currently in API Manager I cannot do simple changes like e.g. add tags, without doing an API upgrade
- all APIs were manually configured by the org admins (i.e. there is no API-Config JSON file) and some of them have no Swagger at all (legacy systems)
- I was not the person that configured the API, but I have to add a couple of e.g. tags to all of them
- now I need to create an API-Config JSON file for each of them with all needed information (i.e. name + path + apiDefinition + org + state + securityProfiles + caCerts) just to update e.g. a couple of tags.

**Additional context**
- if I had a way to preserve all current information already present in API Manager (i.e. name + apiDefinition + org + state + caCerts + securityProfiles + etc) and only add what I really need (i.e. path to find the current API + tags) to the API-Config JSON file, it would be much easier to make global simple API changes by org/api admins that do not own the APIs

**Comment by cwiechmann** [comment]
@remisbaima, I think what you need is the Export-Function to get the actual state of your APIs exported.  

I have worked on that some time ago, but had issues to implement automated tests for it, that's why I never merged the branch back to the main development branch. Now the branch can't be marged due to too many changes. I have to take it over manually.

On this article:
https://community.axway.com/s/article/Simplify-DevOps-with-Axway-API-Manager
Please read the: "What next?" section and let me know, if this is what you need.

**Comment by remisbaima** [comment]
@cwiechmann: the "What next?" would also cover my use-case.
