### ISSUE TITLE
[Bug] Rollback sometimes fails, if FE-API can't be created/configured

### ISSUE THREAD

**Issue by Mitraa-SP** [Axway-API-Management-Plus/apimanager-swagger-promote#129]
**Swagger-Promote Version**
1.6.1-1

**API-Manager and Service-Pack Version**
7.5.3 SP10

**Question**
Hi, If there is no connectivity to the backend host on a given environment, the tool fails to virtualize the API as it is trying to connect to the backend. Is there a property that we can use to disable this so that we could only check if the deployment was successful. 
Currently the deployment fails and FE API gets created but not properly (inbound security/resource path are not configured as per the config file) and the rollback of BE API is failing with "403 message - Cannot delete an API that has been virtualized."

**What I've tried so far**

**Additional information**

**Comment by cwiechmann** [comment]
Hi @Mitraa-SP, The cause for this issue is in the API-Manager itself, as the API-Manager tries to reach out to the Downstream host and if that connection fails, the API-Proxy registration fails. Swagger-Promote cannot change that behavior and only try to handle that situation as good as it can. For instance roll back the "half"-created API.

One thing you can do, is to provide a valid backend-host when importing the API. Swagger-Promote will take that host and adjust the Swagger-File before importing it into the API-Manager. Have a look for parameter backendBasePath:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/2.-Control-API-Configuration#parameter-backendbasepath
Maybe it helps you for your use-case.

Can you share the Log-Messages here, which maybe tells me, why the API can't be rolled back?

**Comment by Mitraa-SP** [comment]
Hi, Thanks for the response. With respect to the rollback, the rollback is not successful as the FE was partially created. It doesn't create with the path that I have given. 
I have attached the error that I get.

![Error](https://user-images.githubusercontent.com/48898943/63327496-a5175000-c371-11e9-97a1-a3490a01be95.JPG)

**Comment by cwiechmann** [comment]
Thanks for that. And yes, that's not perfect. 
The FE-API Creation failed and therefore the API-Manager returns an HTTP 500 Error-Message only. Due to that, Swagger-Promote doesn't know the correct Frontend-API-ID and tries to find it using the Backend-API (limiting it to APIs created the last 2 minutes got), but it doesn't find anything.

**Comment by cwiechmann** [comment]
Has been fixed/enhanced in release 1.6.2.
