### ISSUE TITLE
[Feature] Adding one or more key to identify an API, now it is the frontend URL

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apimanager-swagger-promote#139]
**User story**
Swagger-promote works with the "path" as a key for a unique API.
So if you modify only the value "version", it will update the existing API.
In our use case we would like to be able to keep different versions with the same "path" but only one at a time will be published. Here an example of what is desired as a result in API Manager :
- MyAPI - v1.0.0 - /v1/myapi - unpublished
- MyAPI - v1.1.0 - /v1/myapi - published
- MyAPI - v1.1.1 - /v1/myapi - unpublished

Another use case (that has to be check again) would be to have the exact same configuration except for the organization : 
- MyAPI - v1.0.0 - organization1 - /v1/myapi 
- MyAPI - v1.0.0 - organization2 - /v1/myapi 

**Additional context**
It seems that API Manager accept that, and it is the way the client works with API.

**Comment by cwiechmann** [comment]
Hi @Rennaud, the API-Manager accepts registering the same APIs for the sake of supporting Zero-Downtime-Upgrades of an API. This makes it possible to configure an API completely, before switching it into production without any downtime. 
But, at runtime only one of the registered APIs exposed under the same path will serve the requests. The reason behind: The API-Manager at runtime performs an API-Matching and it can't know which API to select if you have registered more than one.  
That's why, it makes not so much sense to register APIs with different version numbers at the same time. 

There is one exception to that: When using the Query-String-Routing option. In that case, you can register the same API twice and must declare a Query-String-Parameter for each API. Then the API-Manager Runtime will use the combination of the Exposure-Path + Requested-Version to match for the correct API. 
Problem with that: It is a global parameter and once you enable it, you must configure a Query-Version for each API and clients must send from that point on the requested version as the parameter is mandatory for the API-Matching.

Swagger-Promote already supports this in a rudimentary way.  

However, there is an open issue in the same way you are requesting it. See the comment at the end of this issue: #53. 
The Lookup of existing APIs doesn't include the configured Query-String-Version. I need to create a dedicated issue for that to fully support the query-string-option. 

That said, Swagger-Promote will not support other criteria's then the Exposure-Path + the Query-String-Version (when using this option in API-Manager).
