### ISSUE TITLE
[Help] Additional security profile

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apimanager-swagger-promote#141]
**Question**
I manage to add multiple security profiles thanks to "securityProfiles":

> And how then can I link it to the inbound per-method override?
![Capture2](https://user-images.githubusercontent.com/53940634/64183124-a6fd0b00-ce69-11e9-9181-d10116be16fc.PNG)

**What I've tried so far**
I have tried to add two security profile in "securityProfiles":[] , but I am not sure what valuewe have to put instead of "name":"_default" and "isDefault":true. As the documentation said not to change them. So It has been just duplicated with different names ==> KO or it has been changed for name and isDefault ==> KO
By KO we mean : nothing happen. The second security profile is ignored.

**Comment by cwiechmann** [comment]
@Rennaud, It should work when you give it another name and set isDefault to false. I tested it with the following config:
```json
{
   "name":"Samples SecurityInbound APIKey",
   "path":"/samples/securityInbound/apiKey/v1/api",
   "state":"unpublished",
   "version":"1.0.0",
   "organization":"API Development",
   "securityProfiles":[
      {
         "name":"_default",
         "isDefault":true,
         "devices":[
            {
               "name":"API Key",
               "type":"apiKey",
               "order":0,
               "properties":{
                  "apiKeyFieldName":"KeyId",
                  "takeFrom":"HEADER",
                  "removeCredentialsOnSuccess":"false"
               }
            }
         ]
      },
      {
         "name":"Another Security-Profile",
         "isDefault":false,
         "devices":[
            {
               "name":"API Key",
               "type":"apiKey",
               "order":0,
               "properties":{
                  "apiKeyFieldName":"KeyId",
                  "takeFrom":"QUERY",
                  "removeCredentialsOnSuccess":"false"
               }
            }
         ]
      }
   ]
}
```
And this is my API in API-Manager:
![image](https://user-images.githubusercontent.com/16292002/64232183-c2135d80-cef1-11e9-8667-4eb253d0f2a0.png)
Having an additional Security-Profile:
![image](https://user-images.githubusercontent.com/16292002/64232230-d9524b00-cef1-11e9-964c-ea8f4432cd8a.png)

Keep in mind, the additional securityProfile isn't taken into account as long as you don't reference it either for the default-InboundProfile or for a specific method. It's just there for nothing, that's why I'm not sure what you would like to achieve.

Concerning the documentation: Perhaps it needs an update in that area, as it wasn't supported as long as Method-Level settings weren't supported.

**Comment by Rennaud** [comment]
Yes, I also managed to create an additional Security Profile and I changed the issue description just after.
We wanted to link the additional Security Profile to a method using the inbound per-method override.
I saw that the issue #119 managed to do on an outbound a method-level-override.
But I didn't find out if this is not supported or how to do it.

**Comment by cwiechmann** [comment]
Have you checked the documentation?
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/2.6-Method-level-overrides

**Comment by Rennaud** [comment]
ho, my bad. I was searching with "method-level-override" and end with nothing. Didn't pay attention properly on the wiki.

Thanks it answers to my question.
