### ISSUE TITLE
Parameterise Protocol(http/https) in the Script Options

### ISSUE THREAD

**Issue by venu124** [Axway-API-Management-Plus/apimanager-swagger-promote#15]
In case if user's portal runs on http protocol but not on https, we have to get portal available on  https to proceed with the script.
If the port is parameterized, user can proceed with whatever protocol he is using.

**Comment by cwiechmann** [comment]
I think this enhancement is valid and it should be easy to implement.

**Comment by cwiechmann** [comment]
@venu124, I realized that the API-Manager UI/REST-API doesn't support Session-Handling on a plain HTTP-Connection as the session-cookie is set with the "secure" flag. All this happens internal and can't be customized. 
I'm wondering how you are running the API-Manager on a Plain HTTP connection? Can you please explain otherwise I'll close this issue.

Thanks!

**Comment by cwiechmann** [comment]
Won't fix. See comment before.
