### ISSUE TITLE
API Manager 7.5.3, same api name and different resource path creating mutliple apis

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#194]
**Swagger-Promote Version** 1.6.2

**API-Manager and Service-Pack Version**
7.5.3

**Expected behavior**
I have API with name ABC 1 and front end resourcePath as /services/test/v1/rules/record3/cat6cicd
Trying to create ABC 1 and front end resourcePath as /services/test/v1/rules/record3/cat6cicd1. I expect at the end I should see one api. But seeing two APIS with same name ABC 1 but with different resource paths. Please investigate.

**Actual behavior**
I have API with name ABC 1 and front end resourcePath as /services/test/v1/rules/record3/cat6cicd
Trying to create ABC 1 and front end resourcePath as /services/test/v1/rules/record3/cat6cicd1. I expect at the end I should see one api. But seeing two APIS with same name ABC 1 but with different resource paths. Please investigate.

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by cwiechmann** [comment]
Please always use the latest Swagger-Promote version. Bugfixes are not backported.
And I see a difference in your Resource-Paths:
/services/test/v1/rules/record3/cat6cicd
vs.
/services/test/v1/rules/record3/cat6cicd1

Due to that you get two and not one API. If this is a typo in your issue report, please share the log output.

**Comment by hakila** [comment]
In which cases if api exists and api gets created with same name? Is the below behavior exists in all versions above 7.5.3?

**Comment by cwiechmann** [comment]
The name of the API is not a key and therefore not used to identify an existing API. The Key to identify an existing API is the "Exposure path". You have given two different paths:
/services/test/v1/rules/record3/cat6cicd
and 
/services/test/v1/rules/record3/cat6cicd1 
and due to that, you get two different APIs with the same name. That is the behavior right from the very first version.
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/2.-API-Configuration
