### ISSUE TITLE
Service Type is not populated

### ISSUE THREAD

**Issue by rchinthakuntla** [Axway-API-Management-Plus/apimanager-swagger-promote#195]
When I ran the swagger promote script to publish an API, I realized that the "Service Type" column is not populated on the Frontend API. I think the only two options valid are "REST" and "SOAP".

It is critical to differentiate between REST and SOAP API when published in API Manager.

Thanks
Ravee

**Comment by cwiechmann** [comment]
Hi @rchinthakuntla, 

I made some tests and realized, that Swagger-Promote is setting the Service-Type. However, I discovered the following:
You don't see the Service-Type whenever the API must been re-created, due to a change which requires the BE-API to be re-created. For instance, when the Swagger-File has changed. 

And as you know, a new BE-API + FE-API + Grant Access is basically executed. 

Now, the reason why you don't see the Service-Type on the FE-API in the browseris because that information is taken from the belonging BE-API. But if you refresh the FE-APIs only, the browser internally doesn't have the newly created BE-API available and therefore the Service-Type isn't available. 

To make a long story short: Once you refresh also the BE-API (hit F5) the Service-Type is shown again. Can you confirm that?

Cheers,
Chris
