### ISSUE TITLE
[Feature] Add support to API custom fields/properties

### ISSUE THREAD

**Issue by remisbaima** [Axway-API-Management-Plus/apimanager-swagger-promote#253]
**User story**
For our APIs we defined some custom fields/properties. When we use the swagger promote, these custom fields are not reflected in the API "Additional attributes":
![image](https://user-images.githubusercontent.com/1174143/78003950-ba0d8600-7339-11ea-8c67-6f9eefd317d7.png)

**Comment by cwiechmann** [comment]
@remisbaima, do you see the Custom-Field in the API-Manager UI?

**Comment by remisbaima** [comment]
@cwiechmann : yes. I tried to add the screenshot here, but it is not allowing me.

**Comment by cwiechmann** [comment]
If you see the Custom-Properties in the API-Manager UI, they are successfully handled handled by Swagger-Promote. Otherwise you wouldn't see them in the UI. 
Please double check, you are looking at the right API in Cassandra. The table you have to check is: PortalVirtualizedAPI

This is my example:
![image](https://user-images.githubusercontent.com/16292002/78014188-dfa18c00-7347-11ea-8418-59dec1378bb3.png)

**Comment by remisbaima** [comment]
@cwiechmann : sorry, my bad. I forgot to put the properties under "customProperties{...}"
