### ISSUE TITLE
[BUG] Vhost setting inconsistent behavior

### ISSUE THREAD

**Issue by shan916** [Axway-API-Management-Plus/apimanager-swagger-promote#266]
**Swagger-Promote version**
> 1.6.5

**API-Manager and Service-Pack Version**
7.5.3 SP7 or 7.7.20200331

**Expected behavior**
Let's say I have an API published to a specific Vhost in API Manager. Now, I want to change it so the  API is available for all vhosts served by API Manager. I should be able to set the `vhost` to `""` or omit it from the api-config file. This should update the vhost in API Manager properly. This applies to the opposite also where you had an API available to all vhosts but later, you want to restrict it to a specific one.

**Actual behavior**
If you set the `vhost` in the api-config file to '""', the API is treated as a new API. If you omit the `vhost` property in the api-config file, the existing API is not updated.

**Log-Output in Debug**
With `"vhost": ""` in api-config file:
```
0      INFO  nvironmentProperties| Loaded environment properties from file: env.properties.
1977   INFO     APIManagerAdapter| API-Manager version is: 7.7.20200331
2396   INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: 'foo.json' (absolute path)
2399   INFO               Proxies| Sending request to find existing APIs: https://[APIM_HOST]/api/portal/v1.3/proxies?field=path&op=eq&value=%2Ffoo%2Fbar
2608   INFO               Proxies| No existing API found based on filter: [apiPath=/foo/bar vHost= filter=[]]
2609   INFO     APIManagerAdapter| Strategy: No existing API found, creating new!
2611   INFO     APIManagerAdapter| Importing backend API (Swagger/WSDL Import)
2890   INFO     APIManagerAdapter| Create API-Proxy (Front-End API)
6069   INFO     APIManagerAdapter| Updating Frontend-API (Proxy) for the following properties: securityProfiles outboundProfiles corsProfiles path name
6601   INFO  VhostPropertyHandler| Updating V-Host for published API to:
6799   INFO     APIManagerAdapter| Updating Frontend-API (Proxy) for the following properties: vhost
7078   INFO                   App| Successfully replicated API-State into API-Manager
```

With `vhost` omitted from api-config file:
```
0      INFO  nvironmentProperties| Loaded environment properties from file: env.properties.
1898   INFO     APIManagerAdapter| API-Manager version is: 7.7.20200331
2309   INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: 'foo.json' (absolute path)
2311   INFO               Proxies| Sending request to find existing APIs: https://[APIM_HOST]/api/portal/v1.3/proxies?field=path&op=eq&value=%2Ffoo%2Fbar
2515   INFO               Proxies| Found existing API on path: '/foo/bar' (published) (ID: '0057b9fc-b90d-439f-a76f-66c4dc0f8b6f')
2515   INFO               Proxies| Found: 1 exposed API(s)
5051   INFO     APIManagerAdapter| Strategy: Going to update existing API: foo-bar (Version: 1.0)
5052   WARN                   App| No changes detected between Import- and API-Manager-API
No changes detected. Existing with RC: 0
```

**Test case sample**
1. Create an api-config file with a `vhost` value and run swagger promote.
2. Now remove the `vhost` from the api-config file and run swagger promote. The API is not updated.
3. Now set the `vhost` to `""` in the api-config file and run swagger promote. A new API is created instead of the existing one being updated.

I believe #152 broke this. Maybe this should be controllable via a configuration parameter?

**Comment by cwiechmann** [comment]
Hi @shan916, Thanks for reaching out!

I understand your user-case and the requirement how Swagger-Promote should handle it. But the new behavior was implemented on purpose to support the feature to manage multiple APIs at the same time. That's why V-Host and API-Routing-Key became additional criteria for the [Actual-API look-up](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/2.-API-Configuration#how-the-actual-api-is-looked-upped).

To me your requirement comes down to be able to overwrite in some situations how the Actual-API is looked up. Basically not using the Desired-State (having no V-Host) - **instead something else, that includes the previously used V-Host**

With that, the previous VHost-API will be loaded and updated with the desired version not having the V-Host anymore. I think this apporach is more flexible and makes also other processes possible, than just reducing the used criteria to lookup the actual API.

The question I don't have a good answer yet: 
What is an efficient way for the API-Developer/Deployment-Team to add the actual Lookup-Information? 
Given that the information is valid only once, as the API (with the previous V-Host) will be replaced by the "Non-Vhost" API. So, having it version controlled make no real sense.

Options:
- having a dedicated config file (e.g. actual.api-config.json) that contains all keys to lookup the actual API
  - will fail, one the second run
- optional CLI parameter: `-actualVHost tst.customer.com - actualRoutingKey 1.1`
  - might be okay, when calling Swagger-Promote manually in CLI mode
  - have actually no good idea how to integrate that special handling into a pipeline

Let me know your thoughts @shan916. Perhaps you have some other ideas in mind you could share. I want to make sure, to implement the most flexible option which also suits for other customers.

@shan916, is this a side-case or is this kind of V-Host transition part of your regular promotion process?

**Comment by shan916** [comment]
Thanks for the detailed response @cwiechmann. This is a side-case and is not common, but it has come up. From your explanation, it makes sense how it was implemented. I think any solution will be hacky. Worst-case, we just end up with a new API rather than the existing API being updated. I think we can handle this on our side.

**Comment by cwiechmann** [comment]
Okay, then I'll close that issue for now. Please re-open the issue if don't find a practical solution on your side!
