### ISSUE TITLE
[Quota] Application quota is not preserved

### ISSUE THREAD

**Issue by kervoaz** [Axway-API-Management-Plus/apimanager-swagger-promote#43]
Hello,
it seems that specific quota by application is not supported. It should be ok if the script doesn't remove already set quota. This information is lost. Unlucky It is the same behavior that we encouter in the ui. The official API seems to have the rigth behavior (/api/portal/v1.3/applications/:id/quota)

thnak you
![image](https://user-images.githubusercontent.com/5457410/56796395-beb8e880-6812-11e9-97f0-a42021de0dd4.png)

**Comment by cwiechmann** [comment]
@kervoaz, you are right. I assume this happens, when you update an existing APIs, that is already published & subscribed by some applications. 
The reason is, that the API (actually subscribed by applications & quota configured for) is internally replaced a new API and with that, all existing application quotas will be removed, as they are linked to the "old" API.
A potential solution is to load/safe existing application quotas from the API-Manager, before replacing the existing API and re-apply the same quota configuration. 

Would that work for you @kervoaz? Keep in mind, even with that, actual Quota-Consumption values will not be taken over.

**Comment by cwiechmann** [comment]
Now, the tool is loading for all subscribes applications the actual configured quota and takes it over to the newly created API.
This is verified by the new E2E Integration-Test: ValidateAppQuotaStaysTestIT

**Comment by cwiechmann** [comment]
Now also added support to take over Method-Level Application-Quota settings. Forgot this in the first run. Also extended the belonging IntegrationTest.

**Comment by cwiechmann** [comment]
Just released this feature with version 1.5.1 

@kervoaz - I would appreciate your feedback.

**Comment by kervoaz** [comment]
hello, sorry for this late answer and thank you for you quick job. I test the release 1.5.1 and send you feedback asap. thnak you
