### ISSUE TITLE
Application subscription standalone

### ISSUE THREAD

**Issue by kervoaz** [Axway-API-Management-Plus/apimanager-swagger-promote#74]
Hello,

In our dev/deploy cycle, the task to add an api on an application can be done after the first deployment. It can be done by a functional team. At this point, there is no need to recreate the api nor provide the contract. 
In this case, only the api and the app names are needed to add subscription. This task is at the limit between CD and admin task but could be useful. Specially to store these subscriptions in our git repo.
Do we have an existing feature/possibility to reach this goal?  
thanks
Regards Christophe

**Comment by cwiechmann** [comment]
Hi @kervoaz, I'm not 100% sure what you mean. Do you mean you would like to manage application-subscriptions with Swagger-Promote? If yes, this is already possible:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/2.5-Manage-Application-Subscriptions
Otherwise please explain differently what you need?

Thanks!
Chris

**Comment by kervoaz** [comment]
Perfect. It is what I am looking for.
Thank you

**Comment by cwiechmann** [comment]
Great, In that case I close this issue now.
