### ISSUE TITLE
Use the backendBasePath to adjust the Host inside the Swagger-File

### ISSUE THREAD

**Issue by vuvdoan** [Axway-API-Management-Plus/apimanager-swagger-promote#81]
Hi,

I've defined the backendBasePath in the config/contract file and publish my API with the tool. After publishing a frontend API and a backend API were created in the axway API manager. So far so good. 

Unfortunately the backendBasePath is only substituted for the frontend API (backend service url) but not for the backend (base path url). Resulting the certificated cannot be downloaded automatically. 

It seems like this parameter backendBasePath does not have the same effect as having host parameter in the swagger file at all. If a host param is defined in the swagger file and I publish it with the tool. Everything works fine. 

Is this work as designed? I don't want the host param to be defined in the swagger file, since I have multiple stages. Can you please check?

Thanks,
Vu

**Comment by cwiechmann** [comment]
Yes, that's expected behavior as the parameter: backendBasePath controls the API-Manager Proxy-Configuration and is not changing the Swagger-File itself. 
And as the backendBasePath is configured on the FE-API, it has no impact on the Backend-URL. 

Does it makes sense?

**Comment by vuvdoan** [comment]
that's the answer I was afraid of :) Thanks for clarification.
Is there a way to parameterize (actually replace the host param in the swagger file) with this tool?

**Comment by cwiechmann** [comment]
Not at the moment. Perhaps something which can be added later. Should be an easy thing to do, as the Swagger-File is loaded internally anyway.

**Comment by cwiechmann** [comment]
@vuvdoan, As the enhancement makes so much sense, I decided to implement this feature for the next release, which is now done.  
I have even decided to perform this by default (only for JSON Based Swagger-Files). For anybody who don't want this, it can be turned off using the "hidden" parameter: "replaceHostInSwagger" set to false. 

See env.properties.sample for reference in the next release. Can also be used as a normal CLI parameter.

However, the code is implemented in way, if the replace fails for any reason, it is logged with an error message + exception trace, but the tool continues. 
Also please note, as the backendBasePath is now changing the Swagger-File (APIDefinition) the tool will consider it as a changed property. And as a changed API-Definition leads to a Re-Creation of the API, from now on changing the backendBasePath, will re-create the API. In the same way, as it happens when doing any other change in the Swagger-File. Hope this okay?

**Comment by cwiechmann** [comment]
Released with version 1.5.3
